### ISSUE TITLE
new dotPath property is awesome but you should provide a default value if not set

### ISSUE THREAD

**Issue by niluved** [BrianTV98/mind_map#9]
Not everyone knows how to create one Path object. 
Moreover now i'm forced to call a method that builds a Path everywhere i create a mind map in my codebase.

Please consider to provide a default value to 'dotPath' in Mind Map object if null.
thks

**Comment by BrianTran24** [comment]
@niluved 
 We appreciate your contribution. This matter will be looked into promptly.

**Comment by BrianTran24** [comment]
@niluved your issue is fixed at ver 1.0.5. 
Please close this issue

**Comment by niluved** [comment]
thanks

**Comment by niluved** [comment]
closing
